version: '2'
services:
  maven-build:
    build:
      context: .
      dockerfile: build/Dockerfile-build
    image: maven-build:latest
    volumes:
      - ./:/tmp/build/
  app:
    build:
      context: .
      dockerfile: build/Dockerfile-app
    image: java-app:latest
    ports:
      - "8080:8080"
    links:
      - maven-build
    entrypoint:
      - java
      - -jar
      - Vocabulary-1.0-SNAPSHOT.jar
