/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sschudakov.ui;

import com.sschudakov.request.UserRequestManager;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.Collection;
import java.util.List;
import java.util.Map;

/**
 * @author Semen
 */
public class InputWordsJFrame extends javax.swing.JFrame {

    /**
     * Creates new form InputWrodsJFrame
     */
    public InputWordsJFrame() {
        initComponents();

        wordsCollectionsJT.getColumnModel().getColumn(0).setMinWidth(220);
        wordsCollectionsJT.getColumnModel().getColumn(1).setMinWidth(60);
        wordsCollectionsJT.getColumnModel().getColumn(1).setPreferredWidth(60);
        wordsCollectionsJT.getColumnModel().getColumn(0).setPreferredWidth(220);
        this.userRequestManager = new UserRequestManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabbedPane = new javax.swing.JTabbedPane();
        WordPanel = new javax.swing.JPanel();
        wordsLanguageJCB = new javax.swing.JComboBox<>();
        wordsWordValueJTF = new javax.swing.JTextField();
        meaningsJLabel = new javax.swing.JLabel();
        collectionsJLabel = new javax.swing.JLabel();
        wordsMeaningsLanguageJCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        wordsMeaningsJL = new javax.swing.JList<>();
        wordsSaveWordJB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        wordsCollectionsJT = new javax.swing.JTable();
        separator = new javax.swing.JSeparator();
        wordsAddMeaningJB = new javax.swing.JButton();
        wordsAddCollectionJB = new javax.swing.JButton();
        wordsCollectionNameJTF = new javax.swing.JTextField();
        wordClassJLabel = new javax.swing.JLabel();
        wordsWordClassJCB = new javax.swing.JComboBox<>();
        wordsMeaningJTF = new javax.swing.JTextField();
        wordsDeleteMeaningJB = new javax.swing.JButton();
        wordFoundIndidcator = new com.sschudakov.ui.IndicatorLed();
        wordsDeleteWordJB = new javax.swing.JButton();
        CollectionsPanel = new javax.swing.JPanel();
        collectionsLanguageJCB = new javax.swing.JComboBox<>();
        collectionsCollectionNameJTF = new javax.swing.JTextField();
        collectionsAddCollectionJB = new javax.swing.JButton();
        GroupsWordList = new javax.swing.JScrollPane();
        collectionsWordsJL = new javax.swing.JList<>();
        collectionDeleteCollectionJB = new javax.swing.JButton();
        collectionsDeleteWordsJB = new javax.swing.JButton();
        MegaListPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MegaList = new javax.swing.JList<>();
        DeleteWordButton = new javax.swing.JButton();
        MegaListLanguageComboBox = new javax.swing.JComboBox<>();
        languageDeleteWordsJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setPreferredSize(new java.awt.Dimension(600, 500));
        TabbedPane.setRequestFocusEnabled(false);

        WordPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        wordsLanguageJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsLanguageJCBActionPerformed(evt);
            }
        });

        wordsWordValueJTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wordsWordValueJTFKeyPressed(evt);
            }
        });

        meaningsJLabel.setText("Meanings");

        collectionsJLabel.setText("Collections");

        wordsMeaningsLanguageJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsMeaningsLanguageJCBActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(wordsMeaningsJL);

        wordsSaveWordJB.setText("save word");
        wordsSaveWordJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsSaveWordJBActionPerformed(evt);
            }
        });

        jScrollPane2.setPreferredSize(new java.awt.Dimension(280, 326));

        wordsCollectionsJT.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {"My words", null},
                        {"Lesson1", null},
                        {"Lesson2", null},
                        {null, null},
                        {null, null}
                },
                new String[]{
                        "Collection", ""
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        wordsCollectionsJT.setPreferredSize(new java.awt.Dimension(286, 298));
        jScrollPane2.setViewportView(wordsCollectionsJT);

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        wordsAddMeaningJB.setText("add meaning");
        wordsAddMeaningJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsAddMeaningJBActionPerformed(evt);
            }
        });

        wordsAddCollectionJB.setText("add collection");
        wordsAddCollectionJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsAddCollectionJBActionPerformed(evt);
            }
        });

        wordClassJLabel.setText("Class");

        wordsDeleteMeaningJB.setText("remove meaning");
        wordsDeleteMeaningJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsDeleteMeaningJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wordFoundIndidcatorLayout = new javax.swing.GroupLayout(wordFoundIndidcator);
        wordFoundIndidcator.setLayout(wordFoundIndidcatorLayout);
        wordFoundIndidcatorLayout.setHorizontalGroup(
                wordFoundIndidcatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 20, Short.MAX_VALUE)
        );
        wordFoundIndidcatorLayout.setVerticalGroup(
                wordFoundIndidcatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 29, Short.MAX_VALUE)
        );

        wordsDeleteWordJB.setText("delete word");
        wordsDeleteWordJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsDeleteWordJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WordPanelLayout = new javax.swing.GroupLayout(WordPanel);
        WordPanel.setLayout(WordPanelLayout);
        WordPanelLayout.setHorizontalGroup(
                WordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WordPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(WordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(wordsLanguageJCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, WordPanelLayout.createSequentialGroup()
                                                .addGroup(WordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(wordClassJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(wordsWordClassJCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WordPanelLayout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(WordPanelLayout.createSequentialGroup()
                                                                .addGroup(WordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(wordsMeaningsLanguageJCB, 0, 280, Short.MAX_VALUE)
                                                                        .addComponent(wordsAddMeaningJB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(meaningsJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(wordsMeaningJTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(wordsDeleteMeaningJB, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                                                        .addComponent(wordsSaveWordJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(WordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(WordPanelLayout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(collectionsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, WordPanelLayout.createSequentialGroup()
                                                                .addGroup(WordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(wordsDeleteWordJB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(wordsAddCollectionJB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(wordsCollectionNameJTF, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, WordPanelLayout.createSequentialGroup()
                                                .addComponent(wordsWordValueJTF)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(wordFoundIndidcator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(207, 207, 207))
        );
        WordPanelLayout.setVerticalGroup(
                WordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(WordPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(wordsLanguageJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(WordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(wordsWordValueJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(wordFoundIndidcator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(WordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(WordPanelLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(WordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(WordPanelLayout.createSequentialGroup()
                                                                .addComponent(wordClassJLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(wordsWordClassJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(meaningsJLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(wordsMeaningsLanguageJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(wordsDeleteMeaningJB)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(wordsMeaningJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(wordsAddMeaningJB))
                                                        .addGroup(WordPanelLayout.createSequentialGroup()
                                                                .addComponent(collectionsJLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(wordsCollectionNameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(wordsAddCollectionJB)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                .addGroup(WordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(wordsSaveWordJB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(wordsDeleteWordJB))
                                                .addContainerGap())
                                        .addGroup(WordPanelLayout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(separator)
                                                .addGap(40, 40, 40))))
        );

        TabbedPane.addTab("Words", WordPanel);

        collectionsCollectionNameJTF.setToolTipText("Collection name");

        collectionsAddCollectionJB.setText("add collection");
        collectionsAddCollectionJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionsAddCollectionJBActionPerformed(evt);
            }
        });

        GroupsWordList.setViewportView(collectionsWordsJL);

        collectionDeleteCollectionJB.setText("delete collection");
        collectionDeleteCollectionJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionDeleteCollectionJBActionPerformed(evt);
            }
        });

        collectionsDeleteWordsJB.setText("remove words");
        collectionsDeleteWordsJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionsDeleteWordsJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CollectionsPanelLayout = new javax.swing.GroupLayout(CollectionsPanel);
        CollectionsPanel.setLayout(CollectionsPanelLayout);
        CollectionsPanelLayout.setHorizontalGroup(
                CollectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CollectionsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(CollectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(collectionsLanguageJCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(GroupsWordList, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                                        .addComponent(collectionsCollectionNameJTF))
                                .addContainerGap())
                        .addGroup(CollectionsPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(collectionsAddCollectionJB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(collectionDeleteCollectionJB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(collectionsDeleteWordsJB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
        );
        CollectionsPanelLayout.setVerticalGroup(
                CollectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CollectionsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(collectionsCollectionNameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CollectionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(collectionsAddCollectionJB)
                                        .addComponent(collectionDeleteCollectionJB)
                                        .addComponent(collectionsDeleteWordsJB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(collectionsLanguageJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GroupsWordList, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        TabbedPane.addTab("Collections", CollectionsPanel);

        jScrollPane3.setViewportView(MegaList);

        DeleteWordButton.setText("Delete");

        MegaListLanguageComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MegaListLanguageComboBoxItemStateChanged(evt);
            }
        });

        languageDeleteWordsJB.setText("remove words");
        languageDeleteWordsJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageDeleteWordsJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MegaListPanelLayout = new javax.swing.GroupLayout(MegaListPanel);
        MegaListPanel.setLayout(MegaListPanelLayout);
        MegaListPanelLayout.setHorizontalGroup(
                MegaListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MegaListPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MegaListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                                        .addComponent(DeleteWordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(MegaListPanelLayout.createSequentialGroup()
                                                .addComponent(MegaListLanguageComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(languageDeleteWordsJB)))
                                .addContainerGap())
        );
        MegaListPanelLayout.setVerticalGroup(
                MegaListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MegaListPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MegaListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(MegaListLanguageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(languageDeleteWordsJB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteWordButton)
                                .addContainerGap())
        );

        TabbedPane.addTab("Languages", MegaListPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedPane.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void wordsSaveWordJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsSaveWordJBActionPerformed
        String word = this.wordsWordValueJTF.getText();
        String language = (String) this.wordsWordClassJCB.getSelectedItem();
        String wordClass = (String) this.wordsLanguageJCB.getSelectedItem();
        try {
            this.userRequestManager.saveWordInformation(
                    word,
                    wordClass,
                    language
            );
            this.userRequestManager.addMeanings(
                    word,
                    language,
                    extractMeaningsToBeAdded()
            );
            this.userRequestManager.removeMeanings(
                    word,
                    language,
                    extractMeaningsToBeDeleted()
            );
            this.userRequestManager.putInCollections(
                    word,
                    language,
                    extractCollectionsToBeAddedTo()
            );
            this.userRequestManager.removeFromCollections(
                    word,
                    language,
                    extractCollectionsToBeRemovedFrom()
            );
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_wordsSaveWordJBActionPerformed

    private Map<String, Collection<String>> extractMeaningsToBeAdded() {
        throw new UnsupportedOperationException();
    }

    private Map<String, Collection<String>> extractMeaningsToBeDeleted() {
        throw new UnsupportedOperationException();
    }

    private Collection<String> extractCollectionsToBeAddedTo() {
        throw new UnsupportedOperationException();
    }

    private Collection<String> extractCollectionsToBeRemovedFrom() {
        throw new UnsupportedOperationException();
    }


    private void wordsDeleteMeaningJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsDeleteMeaningJBActionPerformed
        throw new UnsupportedOperationException();
    }//GEN-LAST:event_wordsDeleteMeaningJBActionPerformed

    private void wordsAddMeaningJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsAddMeaningJBActionPerformed
        throw new UnsupportedOperationException();
    }//GEN-LAST:event_wordsAddMeaningJBActionPerformed


    private void wordsAddCollectionJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsAddCollectionJBActionPerformed
        try {
            this.userRequestManager.createCollection(this.wordsCollectionNameJTF.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_wordsAddCollectionJBActionPerformed

    private void wordsWordValueJTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordsWordValueJTFKeyPressed
        //todo: this is test implementation, write normal implementation later
        if (wordsWordValueJTF.getText().length() % 2 == 0) {
            wordFoundIndidcator.setColor(IndicatorLed.LedColor.GREEN);
        } else {
            wordFoundIndidcator.setColor(IndicatorLed.LedColor.RED);
        }
        wordFoundIndidcator.repaint();
    }//GEN-LAST:event_wordsWordValueJTFKeyPressed

    private void wordsLanguageJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsLanguageJCBActionPerformed
        throw new UnsupportedOperationException();
    }//GEN-LAST:event_wordsLanguageJCBActionPerformed

    private void wordsMeaningsLanguageJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsMeaningsLanguageJCBActionPerformed
        throw new UnsupportedOperationException();
    }//GEN-LAST:event_wordsMeaningsLanguageJCBActionPerformed

    private void wordsDeleteWordJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsDeleteWordJBActionPerformed
        try {
            this.userRequestManager.deleteWord(
                    this.wordsWordValueJTF.getText(),
                    (String) this.wordsLanguageJCB.getSelectedItem()
            );
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_wordsDeleteWordJBActionPerformed

    private void MegaListLanguageComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MegaListLanguageComboBoxItemStateChanged
        try {
            renderLanguageWords(
                    this.userRequestManager.getWordsByLanguageName(
                            (String) this.MegaListLanguageComboBox.getSelectedItem()));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_MegaListLanguageComboBoxItemStateChanged

    private void languageDeleteWordsJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageDeleteWordsJBActionPerformed
        String language = (String) this.MegaListLanguageComboBox.getSelectedItem();
        for (String s : extractSelectedWords()) {
            try {
                this.userRequestManager.deleteWord(s, language);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_languageDeleteWordsJBActionPerformed

    private void collectionsAddCollectionJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionsAddCollectionJBActionPerformed
        throw new UnsupportedOperationException();
    }//GEN-LAST:event_collectionsAddCollectionJBActionPerformed

    private void collectionDeleteCollectionJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionDeleteCollectionJBActionPerformed
        throw new UnsupportedOperationException();
    }//GEN-LAST:event_collectionDeleteCollectionJBActionPerformed

    private void collectionsDeleteWordsJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionsDeleteWordsJBActionPerformed
        throw new UnsupportedOperationException();
    }//GEN-LAST:event_collectionsDeleteWordsJBActionPerformed

    private List<String> extractSelectedWords() {
        throw new UnsupportedOperationException();
    }

    private void renderLanguageWords(List<String> words) {
        throw new UnsupportedOperationException();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CollectionsPanel;
    private javax.swing.JButton DeleteWordButton;
    private javax.swing.JScrollPane GroupsWordList;
    private javax.swing.JList<String> MegaList;
    private javax.swing.JComboBox<String> MegaListLanguageComboBox;
    private javax.swing.JPanel MegaListPanel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JPanel WordPanel;
    private javax.swing.JButton collectionDeleteCollectionJB;
    private javax.swing.JButton collectionsAddCollectionJB;
    private javax.swing.JTextField collectionsCollectionNameJTF;
    private javax.swing.JButton collectionsDeleteWordsJB;
    private javax.swing.JLabel collectionsJLabel;
    private javax.swing.JComboBox<String> collectionsLanguageJCB;
    private javax.swing.JList<String> collectionsWordsJL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton languageDeleteWordsJB;
    private javax.swing.JLabel meaningsJLabel;
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel wordClassJLabel;
    private com.sschudakov.ui.IndicatorLed wordFoundIndidcator;
    private javax.swing.JButton wordsAddCollectionJB;
    private javax.swing.JButton wordsAddMeaningJB;
    private javax.swing.JTextField wordsCollectionNameJTF;
    private javax.swing.JTable wordsCollectionsJT;
    private javax.swing.JButton wordsDeleteMeaningJB;
    private javax.swing.JButton wordsDeleteWordJB;
    private javax.swing.JComboBox<String> wordsLanguageJCB;
    private javax.swing.JTextField wordsMeaningJTF;
    private javax.swing.JList<String> wordsMeaningsJL;
    private javax.swing.JComboBox<String> wordsMeaningsLanguageJCB;
    private javax.swing.JButton wordsSaveWordJB;
    private javax.swing.JComboBox<String> wordsWordClassJCB;
    private javax.swing.JTextField wordsWordValueJTF;
    // End of variables declaration//GEN-END:variables
    private UserRequestManager userRequestManager;

}
