/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sschudakov.ui;

import com.sschudakov.request.UserRequestManager;

import java.util.List;

/**
 * @author Semen
 */
public class InputWordsJFrame extends javax.swing.JFrame {

    /**
     * Creates new form InputWrodsJFrame
     */
    public InputWordsJFrame() {
        initComponents();

        this.collectionsJT.getColumnModel().getColumn(0).setMinWidth(274);
        this.collectionsJT.getColumnModel().getColumn(1).setMinWidth(20);
        this.collectionsJT.getColumnModel().getColumn(1).setPreferredWidth(20);

        this.userRequestManager = new UserRequestManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        mainJTabbedPane = new javax.swing.JTabbedPane();
        wordTabJP = new javax.swing.JPanel();
        wordLanguageJCB = new javax.swing.JComboBox<>();
        wordJTF = new javax.swing.JTextField();
        meaningJL = new javax.swing.JLabel();
        collectionsJL = new javax.swing.JLabel();
        meaningsLanguageJCB = new javax.swing.JComboBox<>();
        meaningsJlJSP = new javax.swing.JScrollPane();
        meanignsJL = new javax.swing.JList<>();
        applyJB = new javax.swing.JButton();
        collectionsJTJSP = new javax.swing.JScrollPane();
        collectionsJT = new javax.swing.JTable();
        meaningJTF = new javax.swing.JTextField();
        addMeaningJB = new javax.swing.JButton();
        wordClassJCB = new javax.swing.JComboBox<>();
        removeMeaningJB = new javax.swing.JButton();
        collectionsTabJP = new javax.swing.JPanel();
        collectionWordsLanguageJCB = new javax.swing.JComboBox<>();
        collectionJTF = new javax.swing.JTextField();
        createCollectionJB = new javax.swing.JButton();
        collectionWordsJSP = new javax.swing.JScrollPane();
        collectionWordsJL = new javax.swing.JList<>();
        deleteCollectionJB = new javax.swing.JButton();
        languagesTabJP = new javax.swing.JPanel();
        languageWordsJSP = new javax.swing.JScrollPane();
        languageWordsJL = new javax.swing.JList<>();
        deleteWordJB = new javax.swing.JButton();
        allWordsLanguageJCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainJTabbedPane.setToolTipText("");
        mainJTabbedPane.setPreferredSize(new java.awt.Dimension(600, 400));

        wordTabJP.setPreferredSize(new java.awt.Dimension(400, 400));

        wordLanguageJCB.setMaximumRowCount(3);

        meaningJL.setText("Meanings");

        collectionsJL.setText("Collections");

        meaningsLanguageJCB.setMaximumRowCount(3);

        meaningsJlJSP.setViewportView(meanignsJL);

        applyJB.setText("apply");
        applyJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyJBActionPerformed(evt);
            }
        });

        collectionsJT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Collection", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        collectionsJTJSP.setViewportView(collectionsJT);

        addMeaningJB.setText(" add meaning");
        addMeaningJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMeaningJBActionPerformed(evt);
            }
        });

        removeMeaningJB.setText("remove meaning");
        removeMeaningJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMeaningJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wordTabJPLayout = new javax.swing.GroupLayout(wordTabJP);
        wordTabJP.setLayout(wordTabJPLayout);
        wordTabJPLayout.setHorizontalGroup(
            wordTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wordTabJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wordTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wordJTF)
                    .addComponent(applyJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(wordTabJPLayout.createSequentialGroup()
                        .addGroup(wordTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wordLanguageJCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(meaningsLanguageJCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(wordTabJPLayout.createSequentialGroup()
                                .addComponent(meaningJL)
                                .addGap(14, 14, 14))
                            .addComponent(meaningsJlJSP, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(meaningJTF)
                            .addGroup(wordTabJPLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(addMeaningJB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeMeaningJB)
                                .addGap(12, 12, 12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(wordTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wordTabJPLayout.createSequentialGroup()
                                .addGroup(wordTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(collectionsJL)
                                    .addComponent(collectionsJTJSP, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(wordClassJCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        wordTabJPLayout.setVerticalGroup(
            wordTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wordTabJPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(wordJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wordTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordLanguageJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordClassJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wordTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meaningJL)
                    .addComponent(collectionsJL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wordTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wordTabJPLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(meaningJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(meaningsLanguageJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(wordTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeMeaningJB)
                            .addComponent(addMeaningJB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meaningsJlJSP, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addComponent(collectionsJTJSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(applyJB)
                .addGap(6, 6, 6))
        );

        mainJTabbedPane.addTab("Words", wordTabJP);

        collectionWordsLanguageJCB.setMaximumRowCount(3);

        createCollectionJB.setText("create");
        createCollectionJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCollectionJBActionPerformed(evt);
            }
        });

        collectionWordsJSP.setViewportView(collectionWordsJL);

        deleteCollectionJB.setText("delete");
        deleteCollectionJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCollectionJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout collectionsTabJPLayout = new javax.swing.GroupLayout(collectionsTabJP);
        collectionsTabJP.setLayout(collectionsTabJPLayout);
        collectionsTabJPLayout.setHorizontalGroup(
            collectionsTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collectionsTabJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(collectionsTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(collectionWordsLanguageJCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(collectionWordsJSP, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, collectionsTabJPLayout.createSequentialGroup()
                        .addComponent(collectionJTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createCollectionJB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(deleteCollectionJB)))
                .addContainerGap())
        );
        collectionsTabJPLayout.setVerticalGroup(
            collectionsTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collectionsTabJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(collectionsTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collectionJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCollectionJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createCollectionJB))
                .addGap(18, 18, 18)
                .addComponent(collectionWordsLanguageJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(collectionWordsJSP, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainJTabbedPane.addTab("Colelctions", collectionsTabJP);

        languageWordsJSP.setViewportView(languageWordsJL);

        deleteWordJB.setText("delete word");
        deleteWordJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteWordJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout languagesTabJPLayout = new javax.swing.GroupLayout(languagesTabJP);
        languagesTabJP.setLayout(languagesTabJPLayout);
        languagesTabJPLayout.setHorizontalGroup(
            languagesTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagesTabJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(languagesTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(languageWordsJSP, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(languagesTabJPLayout.createSequentialGroup()
                        .addComponent(allWordsLanguageJCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteWordJB)))
                .addContainerGap())
        );
        languagesTabJPLayout.setVerticalGroup(
            languagesTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagesTabJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(languagesTabJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allWordsLanguageJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteWordJB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(languageWordsJSP, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainJTabbedPane.addTab("Languages", languagesTabJP);

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainJTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        mainJTabbedPane.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyJBActionPerformed
        String word = this.wordJTF.getText();
        String wordLanguage = (String) this.wordLanguageJCB.getSelectedItem();
        String wordClass = (String) this.wordClassJCB.getSelectedItem();
        String meaningsLanguage = (String) this.meaningsLanguageJCB.getSelectedItem();
        List<String> collections = extractSelectedCollections();
        List<String> meanings = this.meanignsJL.getSelectedValuesList();

        this.userRequestManager.updateOrSaveWordInformation(
                word,
                wordClass,
                wordLanguage,
                meanings,
                collections,
                meaningsLanguage
        );
    }//GEN-LAST:event_applyJBActionPerformed

    private List<String> extractSelectedCollections() {
        throw new UnsupportedOperationException();
    }

    private void createCollectionJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCollectionJBActionPerformed
        String collectionName = this.collectionJTF.getText();
        this.userRequestManager.createCollection(collectionName);
    }//GEN-LAST:event_createCollectionJBActionPerformed

    private void deleteCollectionJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCollectionJBActionPerformed
        String collectionName = this.collectionJTF.getText();
        this.userRequestManager.deleteCollection(collectionName);
    }//GEN-LAST:event_deleteCollectionJBActionPerformed

    private void deleteWordJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteWordJBActionPerformed
        String word = this.languageWordsJL.getSelectedValue();
        String language = (String) this.allWordsLanguageJCB.getSelectedItem();
        this.userRequestManager.deleteWord(word, language);
    }//GEN-LAST:event_deleteWordJBActionPerformed

    private void addMeaningJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMeaningJBActionPerformed
        String meaning = this.meaningJTF.getText();
        String language = (String) this.meaningsLanguageJCB.getSelectedItem();
        this.userRequestManager.ensureWordExists(meaning, language);
        // display added meaning
        throw new UnsupportedOperationException();
    }//GEN-LAST:event_addMeaningJBActionPerformed

    private void removeMeaningJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMeaningJBActionPerformed
        String meaning = this.meaningJTF.getText();
        String language = (String) this.meaningsLanguageJCB.getSelectedItem();
        this.userRequestManager.removeMeaning(meaning, language);
        throw new UnsupportedOperationException();
    }//GEN-LAST:event_removeMeaningJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputWordsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputWordsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputWordsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputWordsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputWordsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMeaningJB;
    private javax.swing.JComboBox<String> allWordsLanguageJCB;
    private javax.swing.JButton applyJB;
    private javax.swing.JTextField collectionJTF;
    private javax.swing.JList<String> collectionWordsJL;
    private javax.swing.JScrollPane collectionWordsJSP;
    private javax.swing.JComboBox<String> collectionWordsLanguageJCB;
    private javax.swing.JLabel collectionsJL;
    private javax.swing.JTable collectionsJT;
    private javax.swing.JScrollPane collectionsJTJSP;
    private javax.swing.JPanel collectionsTabJP;
    private javax.swing.JButton createCollectionJB;
    private javax.swing.JButton deleteCollectionJB;
    private javax.swing.JButton deleteWordJB;
    private javax.swing.JList<String> languageWordsJL;
    private javax.swing.JScrollPane languageWordsJSP;
    private javax.swing.JPanel languagesTabJP;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JTabbedPane mainJTabbedPane;
    private javax.swing.JList<String> meanignsJL;
    private javax.swing.JLabel meaningJL;
    private javax.swing.JTextField meaningJTF;
    private javax.swing.JScrollPane meaningsJlJSP;
    private javax.swing.JComboBox<String> meaningsLanguageJCB;
    private javax.swing.JButton removeMeaningJB;
    private javax.swing.JComboBox<String> wordClassJCB;
    private javax.swing.JTextField wordJTF;
    private javax.swing.JComboBox<String> wordLanguageJCB;
    private javax.swing.JPanel wordTabJP;
    // End of variables declaration//GEN-END:variables
    private UserRequestManager userRequestManager;
}
